common/models/Manufacturer.php
<?php

namespace common\models;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tbl_manufacturer".
 *
 * @property integer $id
 * @property integer $category_id
 * @property string  $name
 */
class Manufacturer extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'tbl_manufacturer';
    }

    public function rules()
    {
        return [
          ['category_id', 'required'],
          ['category_id', 'integer'],

          ['name', 'required'],
          ['name', 'string', 'max' => 255]
        ];
    }

    public function attributeLabels()
    {
        return [
          'id'          => 'ID',
          'category_id' => 'Категория',
          'name'        => 'Название',
        ];
    }

    /**
     * Возвращает массив key=>value
     * Нужнен для dropDown силектов
     *
     * @return array
     */
    public static function getMap(){

        $oModel = self::find()->asArray()->all();

        return ArrayHelper::map( $oModel, 'id', 'name' );
    }

    /**
     * Возвращает все мануфактуры принадлежащие категории ID и ее руту.
     *
     * Нельзя запросить мануфактуры рутовской категории.
     *
     * @param $id - Категрия
     *
     * @return array $id=>$name
     */
    public static function getMapByCategoryId( $id ){

        $oCategory = CategoryCatalog::findOne( (int)$id );

        if( $oCategory === null || $oCategory->isRoot() ) return [];

        $oModel = self::find()->where( ['category_id'=>[ $oCategory->id, $oCategory->root ]] )->asArray()->all();

        return ArrayHelper::map( $oModel, 'id', 'name' );
    }

    /**
     * Список мануфактур сгруппированных по категории
     *
     * @return array
     */
    public static function getMapGroupByCategory(){

        $oModel = self::find()->asArray()->all();

        return ArrayHelper::map( $oModel, 'id', 'name', 'category_id' );
    }
}

backend/controllers/ManufacturerController.php
<?php

namespace backend\controllers;

use common\models\CategoryCatalog;
use common\models\Manufacturer;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use common\models\User;

class ManufacturerController extends Controller
{
    public function behaviors()
    {
        return [
          'access' => [
            'class' => \yii\filters\AccessControl::className(),

            'only' => ['index', 'delete'],

            'rules' => [
              [
                'actions' => ['index', 'delete'],
                'allow' => true,
                'roles' => [ User::ROLE_ADMIN ],
              ],
            ],
          ],
        ];
    }

	public function actionIndex( $id = null )
	{

        $oModel = $this->_loadModel( $id );

        if( $oModel->load($_POST) && $oModel->save() ){

            Yii::$app->session->setFlash('flash','Мануфактура усепешно сохранена.');

            Yii::$app->getResponse()->redirect( ['manufacturer/index'] );
        }

        $oModelCategories = CategoryCatalog::getTreeMap();

        $oModelList = Manufacturer::getMapGroupByCategory();

		return $this->render('update',[
              'oModel'=>$oModel,
              'oModelList'=>$oModelList,
              'oModelCategories'=>$oModelCategories
          ]);
	}

    public function actionDelete( $id ){

        $this->_loadModel( $id )->delete();

        $this->redirect(['index']);
    }

    protected function _loadModel( $id = null ){

        if( $id === null )
            return new Manufacturer();
        else{

            $oModel = Manufacturer::findOne( (int)$id );

            if( $oModel === null )
                throw new NotFoundHttpException(404, 'Not Found');

            return $oModel;
        }
    }
}

backend/views/manufacturer/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var common\models\Category $oModel
 * @var ActiveForm $form
 * @var array $oModelCategories
 */

?>

<div class="category-update col-xs-8">
    <?php if( !$oModel->isNewRecord ): ?>
        <h4>
            Обновление мануфактуры - <?= $oModel->name ?>
            <a href="<?= Url::to(['/manufacturer/index']); ?>">Создать новую мануфактуру</a>
        </h4>
    <?php else: ?>
        <h4>Создание новой мануфактуры</h4>
    <?php endif; ?>
    <?php if(Yii::$app->session->hasFlash('flash')): ?>
        <div class="alert alert-success">
            <?= Yii::$app->session->getFlash('flash') ?>
        </div>
    <?php endif; ?>

    <div class="row-fluid">

    <?php $form = ActiveForm::begin(); ?>

		<?= $form->field($oModel, 'name') ?>
		<?= $form->field($oModel, 'category_id')->dropDownList( $oModelCategories, ['prompt'=>'-- Выберите категорию --'] ) ?>

		<div class="form-group">
			<?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            <a href="<?= Url::to(['/manufacturer/delete','id'=>$oModel->id]) ?>" class="btn btn-danger">Удалить</a>
        </div>
	<?php ActiveForm::end(); ?>

    </div>

</div><!-- category-update -->

<div id="tree_category" class="col-xs-4">
    <?php foreach( $oModelCategories as $key=>$oCategoryRoot ): ?>
      <div>
        <h3><?= $key ?></h3>
          <ul>
              <?php foreach( $oCategoryRoot as $id=>$oCategory ): ?>
                  <li>
                      <?= $oCategory ?>
                      <?php if (isset($oModelList[$id]) && count($oModelList[$id])): ?>
                          <ul>
                              <?php foreach ($oModelList[$id] as $iManufacturerId => $oModel): ?>
                                  <li>
                                      <a href="<?= Url::to( ['/manufacturer/index', 'id' => $iManufacturerId] ); ?>"><?= $oModel ?></a>
                                  </li>
                              <?php endforeach ?>
                          </ul>
                      <?php endif; ?>
                  </li>
            <?php endforeach; ?>
          </ul>
        </div>
    <?php endforeach; ?>
</div>