common/models/Product.php
<?php

namespace common\models;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tbl_product".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $shop_id
 * @property integer $manufacturer_id
 * @property integer $category_id
 * @property integer $product_group_id
 * @property string $url
 * @property string $price
// * @property string $price
 * @property integer $status
 * @property integer $created
 * @property integer $updated
 * @property integer $amount
 * @property integer $code
 * @property integer $user_id
 * @property integer $count
 *
 * @property CategoryCatalog $category
 * @property Manufacturer $manufacturer
 * @property ProductGroup $productGroup
 * @property Shop $shop
 */
class Product extends \yii\db\ActiveRecord
{
    const DEFAULT_PAGE_SIZE = 10;
    const DEFAULT_ORDER = 'title ASC';
    public $attributesEav = [];

    const STATUS_PUBLISHED = 1;
    const STATUS_NOT_PUBLISHED = 0;

    const STATUS_STOCK = 1;
    const STATUS_ON_ORDER = 2;
    const STATUS_NOT_AVAILABLE = 3;

    protected static $_STATUS_PUBLISHED_TITLE = [
        self::STATUS_PUBLISHED => 'Опубликовано',
        self::STATUS_PUBLISHED => 'Не опубликовано',
    ];

    protected static $_STATUS_TITLE = [
      self::STATUS_STOCK         => 'В наличии',
      self::STATUS_ON_ORDER      => 'Под заказ',
      self::STATUS_NOT_AVAILABLE => 'Нет в наличии',
    ];

    public static function getPublishedTitleByStatusCode( $iCode ){
        return static::$_STATUS_PUBLISHED_TITLE[ $iCode ];
    }

    public static function getTitleByStatusCode( $iCode ){
        return static::$_STATUS_TITLE[ $iCode ];
    }

    public static function getMapStatus(){
        return static::$_STATUS_TITLE;
    }

    public function getStatusTitle(){
        return self::$_STATUS_TITLE[ $this->status ];
    }

	public static function tableName()
	{
		return 'tbl_product';
	}

	public function rules()
	{
		return [
            ['shop_id','required'],
            ['shop_id','integer'],

            ['user_id','required'],
            ['user_id','integer'],

            ['manufacturer_id','required'],
            ['manufacturer_id','integer'],

            ['category_id','required'],
            ['category_id','integer'],

            ['product_group_id','required'],
            ['product_group_id','integer'],

            ['is_published','integer'],

            ['count','validationCount'],
            ['count','required'],
            ['count','integer'],

            ['status','required'],
            ['status','integer'],

            ['created','integer'],

            ['updated','integer'],

            ['code','integer'],

            ['description', 'string'],
            ['description', 'filter', 'filter' => function ($value) {
                  return nl2br( \common\filters\HtmlPurifier::escape( $value, 'br') );
            }],

            ['price','required'],
            ['price','number'],

            ['title','required'],
            ['title', 'filter', 'filter' => function ($value) {
                  return \common\filters\HtmlPurifier::escape( $value );
            }],

            ['url','required'],
            ['url', 'filter', 'filter' => function ($value) {
                  return \common\filters\HtmlPurifier::escape( $value );
            }],

            ['amount','integer'],

            ['attributesEav','safe']
		];
	}

	public function attributeLabels()
	{
		return [
          'id'               => 'ID',
          'title'            => 'Название',
          'description'      => 'Описание',
          'shop_id'          => 'Магазин',
          'manufacturer_id'  => 'Производитель',
          'category_id'      => 'Категория товара',
          'product_group_id' => 'Группа товара',
          'url'              => 'Url',
          'price'            => 'Стоимость, $',
          'status'           => 'Статус',
          'created'          => 'Дата создания',
          'updated'          => 'Дата обновления',
          'amount'           => 'Скидка, %',
          'code'             => 'Код товара',
          'count'            => 'Количество на складе (шт.)',
          'is_published'     => 'Опубликовать в каталоге товаров',
		];
	}

    public function behaviors()
    {
        return [
          'slug' => [
            'class'         => 'common\components\behaviors\Slug',
            'in_attribute'  => 'title',
            'out_attribute' => 'url',
            'translit'      => true
          ]
        ];
    }

    public function beforeSave( $insert )
    {
        if( $this->isNewRecord ){

            $this->created = time();
            $this->code    = time();
        }

        $this->updated = time();

        return parent::beforeSave( $insert );
    }



    public function validationCount($attribute) {
        if( $this->status == static::STATUS_STOCK && $this->$attribute <= 0 ){
            $this->addError($attribute, 'Укажите количество товара на складе. Количество должно быть больше нуля.');
        }elseif( $this->status != static::STATUS_STOCK && $this->$attribute > 0 ){
            $this->addError($attribute, 'Количество товара не может быть больше нуля, так как у Вас нет его в наличии.');
        }
    }

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getCategory()
	{
		return $this->hasOne(CategoryCatalog::className(), ['id' => 'category_id']);
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getManufacturer()
	{
		return $this->hasOne(Manufacturer::className(), ['id' => 'manufacturer_id']);
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getProductGroup()
	{
		return $this->hasOne(ProductGroup::className(), ['id' => 'product_group_id']);
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getShop()
	{
		return $this->hasOne(Shop::className(), ['id' => 'shop_id']);
	}

    /**
     * @return \yii\db\ActiveRelation
     */
    public function getImages()
    {
        return $this->hasMany(ProductImages::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveRelation
     */
    public function getMainImage()
    {
        return $this->hasOne(ProductImages::className(), ['product_id' => 'id'])->where(['is_main'=>1]);
    }

    /**
     * TODO: via
     * Атрибуты группы товара
     * @return mixed
     */
    public function getAttachAttributes(){
      return  $this->hasMany( Attributes::className(), ['id'=>'attribute_id'])
                   ->viaTable('tbl_attribute_group', ['product_group_id' => 'product_group_id']);
    }

    /**
     * Значения заполненных атрибутов.
     * @return mixed
     */
    public function getAttachAttributesValues(){
        return $this->hasMany( AttributesValue::className(), ['id'=>'attribute_value_id'])
          ->viaTable('tbl_attributes_relation', ['product_id' => 'id'])->asArray();
    }

    /**
     * Получить массив EAV элементов.
     * Массив содержит тип элемента, значение, если оно заполнено
     * Массив значений, если это список
     * Название атрибута
     * Данный метод мы вызываем из view файла.
     *
     * @return array
     */
    public function getEav(){

        $aResult = [];

        $oModelAttachAttributes = $this->attachAttributes;


        foreach( $oModelAttachAttributes as $oAttribute ){

            $aResult[$oAttribute->id]['title'] = $oAttribute->title;
            $aResult[$oAttribute->id]['type']  = $oAttribute->type;
            $aResult[$oAttribute->id]['name'] = 'Product[attributesEav]['.$oAttribute->id.']';

            if( $oAttribute->type == Attributes::TYPE_LIST ){
                $aResult[$oAttribute->id]['value'] = $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_LIST );
                $aResult[$oAttribute->id]['values']   = $oAttribute->getMapValues();
                $aResult[$oAttribute->id]['is_multi'] = $oAttribute->is_multi;

            }elseif( $oAttribute->type == Attributes::TYPE_BOOLEAN ){
                $aResult[$oAttribute->id]['value'] = $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_BOOLEAN );
                $aResult[$oAttribute->id]['values']   = Attributes::getMapBooleanLabels();

            }elseif( $oAttribute->type == Attributes::TYPE_INTEGER ){
                $aResult[$oAttribute->id]['value'] = $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_INTEGER );
            }

        }
        return $aResult;
    }

    public function getEavFront(){
        $aResult = [];

        $oModelAttachAttributes = $this->attachAttributes;

        foreach( $oModelAttachAttributes as $oAttribute ){

            $aResult[$oAttribute->id]['title'] = $oAttribute->title;
            $aResult[$oAttribute->id]['type']  = $oAttribute->type;

            if( $oAttribute->type == Attributes::TYPE_LIST ){
                $aResult[$oAttribute->id]['value'] = '';

                $aProductValue = $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_LIST );

                $aAttributeValues = $oAttribute->getMapValues();

                foreach( $aProductValue as $iIdValue ){

                    $aResult[$oAttribute->id]['value'][] = $aAttributeValues[ $iIdValue ];

                }

            }elseif( $oAttribute->type == Attributes::TYPE_BOOLEAN ){

                $aProductValue = $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_BOOLEAN ) ? 1 : 0;

                $aAttributeValues = Attributes::getMapBooleanLabels();

                $aResult[$oAttribute->id]['value'] = [ $aAttributeValues[$aProductValue] ];

            }elseif( $oAttribute->type == Attributes::TYPE_INTEGER ){

                $aResult[$oAttribute->id]['value'] = [ $this->getValueByAttribute( $oAttribute->id, Attributes::TYPE_INTEGER ) ];
            }

        }

        foreach( $aResult as $key=>$aResultItem){
            if( !is_array($aResultItem['value'])) unset($aResult[$key]);
        }

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use common\models\LoginForm;
use common\models\User;

class SiteController extends Controller
{

    public function behaviors()
    {
        return [
          'access' => [
            'class' => \yii\filters\AccessControl::className(),
            'only'  => ['index', 'delete'],
            'rules' => [
              [
                'actions' => ['login', 'error'],
                'allow'   => true,
              ],
              [
                'actions' => ['index', 'build-rbac', 'logout'],
                'allow'   => true,
                'roles'   => [User::ROLE_ADMIN],
              ],
            ],
          ],
        ];
    }

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex()
	{
		return $this->render('index');
	}

	public function actionLogin()
	{
		if (!\Yii::$app->user->isGuest) {
			$this->goHome();
		}

		$model = new LoginForm();
		if ($model->load($_POST) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}

    public function actionBuildRbac(){

        $auth = \Yii::$app->getAuthManager();

        $rule = new \common\rbac\RetailRule();
        $auth->add($rule);

        $retail = $auth->createRole('retail');
        $retail->ruleName = $rule->name;
        $auth->add($retail);

        $rule = new \common\rbac\AdministratorRule();
        $auth->add($rule);

        $admin = $auth->createRole('administrator');
        $admin->ruleName = $rule->name;
        $auth->add($admin);
        $auth->addChild($admin, $retail);

        $auth->save();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Product;
use Yii;
use yii\web\Controller;

class SiteController extends Controller
{

	public function behaviors()
	{
		return [
			'access' => [
				'class' => \yii\filters\AccessControl::className(),
				'only' => ['login', 'logout', 'signup'],
				'rules' => [
					[
						'actions' => ['signup','login'],
						'allow' => true,
						'roles' => ['?'],
					],
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					]
				],
			],
		];
	}

    public function actions()
    {
        return [
          'error' => [
            'class' => 'yii\web\ErrorAction',
          ],
        ];
    }

	public function actionIndex()
	{
        //Todo Published
        $oModelProducts = Product::find()->limit(10)->orderBy('id DESC')->all();
		return $this->render('index', ['oModelProducts' => $oModelProducts]);
	}
}

frontend/views/site/about.php
<?php
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
	<h1><?= Html::encode($this->title) ?></h1>

	<p>This is the About page. You may modify the following file to customize its content:</p>

	<code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var app\models\ContactForm $model
 */
$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
	<h1><?= Html::encode($this->title) ?></h1>

	<p>
		If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
	</p>

	<div class="row">
		<div class="col-lg-5">
			<?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
				<?= $form->field($model, 'name') ?>
				<?= $form->field($model, 'email') ?>
				<?= $form->field($model, 'subject') ?>
				<?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
				<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
					'options' => ['class' => 'form-control'],
					'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
				]) ?>
				<div class="form-group">
					<?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
				</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>

</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var string $name
 * @var string $message
 * @var Exception $exception
 */

$this->title = $name;
?>
<div class="site-error">

	<h1><?= Html::encode($this->title) ?></h1>

	<div class="alert alert-danger">
		<?= nl2br(Html::encode($message)) ?>
	</div>

	<p>
		The above error occurred while the Web server was processing your request.
	</p>
	<p>
		Please contact us if you think this is a server error. Thank you.
	</p>

</div>

frontend/views/site/index.php
<div class="wrapper product-container-w">
    <div class="row">
        <div class="col-xs-12 header">
            <ul class="left">
                <li>
                    <a href="">Лучшие товары</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row product-container">
        <div class="col-xs-12">
            <?php foreach( $oModelProducts as $oModelProduct ): ?>
                <div class="col-xs-3 item">
                    <div class="header">
                        <span>Продавец и рейтинг</span>
                        <div class="star">
                        <?= \frontend\widgets\Raty::widget(['value'=>1]) ?>
                        </div>
                        <div class="clear store">Продавец "<?= $oModelProduct->shop->title ?>"</div>
                    </div>
                    <img src="<?= $oModelProduct->mainImage ? $oModelProduct->mainImage->getUrl(170,160) : 'http://placehold.it/170x160' ?>" alt="<?= $oModelProduct->shop->title ?> - <?= $oModelProduct->manufacturer->name ?> <?= $oModelProduct->title ?>"/>
                   <a class="title" href="<?= \yii\helpers\Url::to(['product/view', 'url'=>$oModelProduct->url]) ?>"> <strong><?= $oModelProduct->manufacturer->name ?> <?= $oModelProduct->title ?></strong></a>
                    <div class="price"><strong><?= $oModelProduct->price ?>$</strong></div>
                    <div class="control">
                        <span class="count">В наличии <?= $oModelProduct->count ?> шт.</span>
                        <a href="<?= \yii\helpers\Url::to(['order/create', 'id'=>$oModelProduct->id]) ?>" onclick="return false;" class="btn btn-primary add-basket fancybox.ajax">Куплю</a>
                    </div>
                </div>
            <?php endforeach; ?>

        </div>
    </div>
</div>

<div class="indent-bottom"></div>

<div class="wrapper news">
    <h1>Новости недели</h1>

    <div class="row news-container">
        <div class="col-xs-4 item">
            <center>
            <img src="http://placehold.it/240x130" alt=""/>
            </center>
            <h2>
                <a href="">Уникальные профессии. Кремовар: «Не стоит </a>
            </h2>
            <div class="description">
                Onliner.by продолжает рассказывать о людях с уникальными профессиями. Сегодня в цикле «Работа» кремовар Юлия Титова рассказала нам, как стала этим заниматься, какие косметические продукты и ингредиенты особенно вредны для здоровья и почему белорусская косметика не хуже импортной премиум-класса.
            </div>
        </div>
        <div class="col-xs-4 item">
            <center>
            <img src="http://placehold.it/240x130" alt=""/>
            </center>
            <h2>
                <a href="">Уникальные профессии. Кремовар: «Не стоит </a>
            </h2>
            <div class="description">
                Onliner.by продолжает рассказывать о людях с уникальными профессиями. Сегодня в цикле «Работа» кремовар Юлия Титова рассказала нам, как стала этим заниматься, какие косметические продукты и ингредиенты особенно вредны для здоровья и почему белорусская косметика не хуже импортной премиум-класса.
            </div>

        </div>
        <div class="col-xs-4 item">
            <center>
            <img src="http://placehold.it/240x130" alt=""/>
            </center>
            <h2>
                <a href="">Уникальные профессии. Кремовар: «Не стоит </a>
            </h2>
            <div class="description">
                Onliner.by продолжает рассказывать о людях с уникальными профессиями. Сегодня в цикле «Работа» кремовар Юлия Титова рассказала нам, как стала этим заниматься, какие косметические продукты и ингредиенты особенно вредны для здоровья и почему белорусская косметика не хуже импортной премиум-класса.
            </div>

        </div>
    </div>
</div>

<div class="indent-bottom"></div>

<div class="wrapper">
    <div class="about">
        <h3 class="b-posts-1-item__title"><span>Манифест</span></h3>
            <p>Наша цель — предоставлять читателям максимально полную, непредвзятую и точную информацию о технике, а также помогать покупателям находить лучшие модели по минимальным ценам.<br></p>
            <h3>Редакционная политика</h3>
            <p>Статьи и новости сайта Onliner.by отражают только точку зрения автора. Материалы, размещенные на сайте, не продаются ни в каком виде. У нас нет заказных статей, новостей или обзоров.<br></p>
            <p>Мы уверены, что в любом уважающем себя издании между коммерческим и редакционным отделами должна вырасти стена, пробить которую не должен ни один доллар. Угрозы снять рекламу из-за острого материала на нас не действуют.<br></p>
            <p>Мы считаем, что проплаченные материалы недостойны называться «пиаром» и вызывают у целевой аудитории только отвращение. Мы готовы совершенно бесплатно и в наиболее полной форме писать об информационных поводах любых компаний.<br></p>
            <p>Мы равноудалены от всех компаний на рынке, деятельность которых описывается в материалах. Никакие бутерброды на фуршетах не заставят нас изменить свою редакционную позицию.<br></p>
    </div>
</div>